CREATE TABLE HOTELS (
    Name VARCHAR(15) NOT NULL
    , Region INT NOT NULL
    , Address VARCHAR(30)
    , Image VARCHAR(10)
    , Accessibility INT
    , Gym INT
    , Spa INT
    , PRIMARY KEY(name
));

CREATE TABLE ROOMS (
    Rnumber INT NOT NULL
    , Hname VARCHAR(15) NOT NULL
    , Price INT NOT NULL
    , Wifi INT ,Breakfast INT
    , Beds INT NOT NULL
    , Adults INT NOT NULL
    , Children INT
    , PRIMARY KEY(Rnumber,Hname)
    , FOREIGN KEY(Hname) REFERENCES HOTELS(Name
));

CREATE TABLE RESERVATIONS (
    ReservationID VARCHAR(20) NOT NULL
    , CreateDate BIGINT NOT NULL
    , StartDate BIGINT NOT NULL
    , EndDate BIGINT NOT NULL
    , Cancelled INT NOT NULL
    , Paid INT NOT NULL
    , Contact VARCHAR(30) NOT NULL
    , Hname VARCHAR(15) NOT NULL
    , Rnumber INT NOT NULL
    , PRIMARY KEY(ReservationID)
    , FOREIGN KEY(Hname,Rnumber) REFERENCES ROOMS(Hname,Rnumber)
);

CREATE TABLE REVIEWS (
    Grade INT NOT NULL
    , Hname VARCHAR(15) NOT NULL
    , Rnumber INT NOT NULL
    , Text VARCHAR(280)
    , ResID VARCHAR(20) NOT NULL
    , PRIMARY KEY(ResID)
    , FOREIGN KEY(ResID) REFERENCES RESERVATIONS(ReservationID)
    , FOREIGN KEY(Hname,Rnumber) REFERENCES ROOMS(Hname,Rnumber)
);

INSERT INTO HOTELS VALUES('Hotel_1',0,NULL,NULL,0,0,0);
INSERT INTO HOTELS VALUES('Hotel_2',1,NULL,NULL,0,0,0);
INSERT INTO HOTELS VALUES('Hotel_3',2,NULL,NULL,0,0,0);
INSERT INTO HOTELS VALUES('Hotel_4',3,NULL,NULL,0,0,0);
INSERT INTO HOTELS VALUES('Hotel_5',4,NULL,NULL,0,0,0);
INSERT INTO HOTELS VALUES('Hotel_6',5,NULL,NULL,0,0,0);

INSERT INTO ROOMS VALUES(101,'Hotel_1',30000,0,0,1,1,0);
INSERT INTO ROOMS VALUES(102,'Hotel_1',30000,1,0,1,1,0);
INSERT INTO ROOMS VALUES(101,'Hotel_2',30000,0,0,1,1,0);
INSERT INTO ROOMS VALUES(101,'Hotel_3',30000,0,0,1,1,0);
INSERT INTO ROOMS VALUES(101,'Hotel_4',30000,0,0,1,1,0);
INSERT INTO ROOMS VALUES(101,'Hotel_5',30000,0,0,1,1,0);
INSERT INTO ROOMS VALUES(101,'Hotel_6',30000,0,0,1,1,0);
